### ISSUE TITLE
Unable to get this to work on Mac OS Sierra

### ISSUE THREAD

**Issue by qwitwa** [zanaca/docker-dns#5]
This is just a quick note to say that I was unable to get this to work on Mac OS Sierra. I modified the sed line and the requirements as mentioned in previous issues, and managed to get what seemed like a tunnel working, but attempting to access a docker image with unexposed ports lead to a "This connection was reset" message in the browser and multiple messages similar to "server: warning: closed channel 1 got cmd=TCP_DATA len=325" printed in the console where the tunnel was running. 

Also, I'm not sure I understand the instruction to check that things are working by pinging ns0.docker. sshuttle doesn't forward icmp, and I pinging ns0.docker just resulted in timeout messages.

**Comment by wandergeek** [comment]
+1 no dice here either

**Comment by zanaca** [comment]
Could you please confirm that the problem still occurs on Sierra? I changed a lot the script to work on High Sierra and made the `dockerdns-tunnel.plist` work on boot!

The ping issue just occurs on mac, I just discovered that sshuttle does not handles ICMP.  So I changed that message from `ping ns0.docker` to `nc -v ns0.docker 53`
```
found 0 associations
found 1 connections:
     1:	flags=82<CONNECTED,PREFERRED>
	outif en2
	src 192.168.192.12 port 51076
	dst 172.17.0.2 port 53
	rank info not available
	TCP aux info available

Connection to ns0.docker port 53 [tcp/domain] succeeded!
```

The "server warning: closed" thing is reported on sshuttle (https://groups.google.com/forum/#!topic/sshuttle/hTMW2OCpAmk)[forum].

You tried to access a webpage hosted in a docker container? If yes, what output you get when you run `curl -v http://CONTAINER_NAME.docker` ?

**Comment by zanaca** [comment]
It is related to #1

**Comment by krazzer** [comment]
Not working for me on High Sierra either. 

`curl -v https://container.docker` gives timeout:

```
* Rebuilt URL to: https://container.docker/
*   Trying 172.18.0.19...
* TCP_NODELAY set
* Connection failed
* connect to 172.18.0.19 port 443 failed: Operation timed out
* Failed to connect to container.docker port 443: Operation timed out
* Closing connection 0
```

I would love to have this work!

**Comment by zanaca** [comment]
@krazzer  On MacOS you should check if the tunnel (macos-tunnel.sh) is running...   We are using docker-dns on all development stage at my company in a mixed macbooks, ubuntus and fedoras environment.

The sshuttle is "under control" right now.

if you run `nc -v container.docker 53` and see a successful connection you have a working DNS, but the container is not listening  on port 80

**Comment by jgreenman** [comment]
@zanaca below is what I am seeing on High Sierra.

* Added the `/etc/resolver/docker` file with the right nameserver.
* nc -v container.docker 53 indicates success.
* Nginx container service resolves on the loop back device for example `0.0.0.0` on port 80.
* When I ping name.docker it resolves to an ip within the subnet range of the dns service. 
* When I watch the logs of the docker container it notes that the dns service is aware of the docker-compose service.

What I believe I am missing is how to setup the docker-compose containers so that they are properly listening.  Do you have an example docker-compose setup that you can share.  Beyond the dns docker container and /etc/resolver files what other elements need to be setup specifically for docker-compose.

**Comment by jgreenman** [comment]
A colleague noted that we were missing `network_mode: bridge` in our docker-compose file.  I also needed to remove the images and recreate them.

**Comment by zanaca** [comment]
Sorry for the looooong delay.
Actually you don't need docker-compose to make anything work... because with docker-dns you don't  need to bind anything... all containers will be visible using the domain you configured.

Sure you can use docker-compose as usual, but you don't need to use (or bind) docker-dns on your yaml. But sure, docker-dns MUST be started before any other container so it can create handle all new container names  to be displayed as $containername.$DOMAIN_CHOSEN

**Comment by zanaca** [comment]
Closing for no update. 

Should start using version 2.0
