### ISSUE TITLE
usage questions

### ISSUE THREAD

**Issue by scottlaplante** [zanaca/docker-dns#8]
Hello. Like many before me, I've been struggling with Docker For Mac's lack of ability to "just work" when it comes to custom IPs, local dev domain names, and controlling how ports are working. This project of yours seems very compelling, but I'm having problems getting it to work. Here are some questions which might help spur me along:

1. Does this work with docker-compose? If so, do we have to use network_mode:bridge? I've tried various combinations without success.
2. On current master:HEAD (6a48b89938edb182daf206b4f1e64ecf540a55df) I receive `make: *** [tunnel] Error 1` during the sshuttle command. When I went back to the high sierra commit (9bde1701f67cef78e9c19fd602b67f91a346f34e) it worked "better", though I was still unsuccessful. It appears that if I manually kill the sshuttle pids, things run better. (sorry for the lack of specifics here!)
3. If a container is brought up after the ns0 is run, is the expectation/intent that the dns will map? Or do we have to run `make tunnel` at that point?

Here is a use case I've tried:
1. Starting point: `docker kill $(docker ps -q) && docker rm $(docker ps -a -q)`
2. First bring up ns0: `make install` -- receive `Now all of your containers are reachable using CONTAINER_NAME.docker inside and outside docker. E.g.: nc -v ns0.docker 53`
3. Run a simple container: `docker run -d --name test nginx`
4. `curl http://test.docker` fails (could not resolve host)
5. Attempt `make tunnel`. Receive `make: *** [tunnel] Error 1`
6. kill all sshuttle-related pids and try `make tunnel` again. Receive `make: *** [tunnel] Error 99`
7. re-run `make install`. Receive the success message (now all your containers...)
8. `curl http://test.docker` fails still, same could not resolve.

To say I'm invested in getting this working would be an understatement. Please tell me where I'm (clearly) going wrong!

mac: high sierra (10.13.2)
docker: Docker version 17.09.1-ce, build 19e2cf6
docker for mac: 17.09.1-ce-mac42

**Comment by zanaca** [comment]
The only thing it does is expose docker containers names as domain for requests, and in mac, redirect all requests through the tunnel.

Never tested in docker-compose, because the thing that composes do is to link the containers internally, and with `docker-dns` it is not required because the domain is visible within docker and for the host machine.  Personally I can't see why it would not work.

The `sshuttle` is really a point of concern, since the launch of that project there's a [issue](1) to remove it and a simple solution, is to use some openvpn inside the docker container, but I don't like it very much.

When you finish the installation in mac you need to make sure that the tunnel is up. The installation process starts tunnel in background, but after each reboot you need to run `make tunnel` to turn it on again...  The thing is that your  DNS is pointing to the docker network, but as you can't talk to that network, nothing happens.  After the tunnel is up, you will have "route" to docker dns...

**Comment by scottlaplante** [comment]
Thanks for the explanation. I've had to shift priorities so I won't be able to focus on this for a while. Closing because there isn't really an "issue" I can pinpoint, per se. Thanks again.
